dist: bionic
language: cpp
notifications:
  email: false
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc-8
      env:
        - COMPILER_NAME=gcc
        - GCC_VERSION=8
        - CC=gcc-8
        - CXX=g++-8
        - MATRIX_EVAL="CXX=g++-8 && CC=gcc-8"
      cache:
        apt: true
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-8
            - g++-8
    - os: linux
      compiler: clang-9
      env:
        - COMPILER_NAME=clang
        - CXX=clang++-9
        - CC=clang-9
        - CLANG_VERSION=9
        - MATRIX_EVAL="CXX=clang++-9 && CC=clang-9"
      cache:
        apt: true
      addons:
        apt:
          update: true
          sources:
            - sourceline:  'ppa:ubuntu-toolchain-r/test'
            - sourceline:  'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-snapshot main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-9-dev
            - clang-9
            - libstdc++-9-dev

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user conan cmake
  - # Get a more recent version of CMake
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - export CMAKE_INSTALL_SCRIPT=cmake-3.14.0-Linux-x86_64.sh
  - wget https://github.com/Kitware/CMake/releases/download/v3.14.0/${CMAKE_INSTALL_SCRIPT}
  - chmod +x ${CMAKE_INSTALL_SCRIPT}
  - ./${CMAKE_INSTALL_SCRIPT} --prefix=$HOME/usr --exclude-subdir --skip-license

script:
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
  - cmake --build build
  - cd build && ctest
